from __future__ import annotations

import base64
from typing import Any

import cv2
import numpy as np


class FitCardService:
    """Render shareable SmartFit profile cards as image data URLs."""

    def render_from_scan(self, profile_name: str, scan: dict[str, Any]) -> str:
        width, height = 1080, 1320
        canvas = np.full((height, width, 3), 248, dtype=np.uint8)

        self._draw_gradient_header(canvas)

        self._draw_text(canvas, "My SmartFit Profile", (60, 92), 1.2, (255, 255, 255), 3)
        self._draw_text(canvas, f"Profile: {profile_name}", (60, 132), 0.72, (230, 240, 255), 2)

        self._draw_text(canvas, f"Predicted Size: {scan.get('predicted_size', '-')}", (60, 222), 0.95, (16, 24, 40), 2)
        confidence_percent = float(scan.get("confidence", 0.0)) * 100.0
        self._draw_text(canvas, f"Confidence: {round(confidence_percent, 1)}%", (60, 264), 0.72, (35, 50, 75), 2)

        fit_preference = scan.get("fit_preference", "regular")
        self._draw_text(canvas, f"Fit Preference: {fit_preference.title()}", (60, 302), 0.72, (35, 50, 75), 2)

        risk = scan.get("return_risk", {})
        risk_text = f"Return Risk: {risk.get('level', 'low').title()} ({risk.get('score', 0)})"
        self._draw_text(canvas, risk_text, (60, 340), 0.72, (35, 50, 75), 2)

        self._draw_section_box(canvas, (40, 390), (1040, 650), "Measurements")
        measurements = scan.get("measurements", {})
        row_y = 455
        for metric in ["chest", "waist", "shoulder"]:
            metric_label = metric.title()
            metric_value = measurements.get(metric, "-")
            self._draw_text(canvas, f"{metric_label}: {metric_value}", (70, row_y), 0.72, (20, 30, 50), 2)
            row_y += 55

        self._draw_section_box(canvas, (40, 680), (1040, 980), "Brand Mapping")
        mapping = scan.get("brand_mapping", {})
        row_y = 745
        for brand, size in list(mapping.items())[:8]:
            self._draw_text(canvas, f"{brand}: {size}", (70, row_y), 0.68, (20, 30, 50), 2)
            row_y += 45

        self._draw_section_box(canvas, (40, 1010), (1040, 1260), "Generated by SmartFit AI")
        self._draw_text(canvas, "AI-based body measurements and personalized sizing", (70, 1085), 0.66, (35, 50, 75), 2)
        self._draw_text(canvas, "Use this card while shopping across brands.", (70, 1130), 0.66, (35, 50, 75), 2)

        is_ok, encoded = cv2.imencode(".png", canvas)
        if not is_ok:
            raise ValueError("Unable to render fit card image.")

        payload = base64.b64encode(encoded.tobytes()).decode("utf-8")
        return f"data:image/png;base64,{payload}"

    @staticmethod
    def _draw_gradient_header(canvas: np.ndarray) -> None:
        header_height = 170
        for y in range(header_height):
            alpha = y / max(header_height - 1, 1)
            color = (
                int(210 - 110 * alpha),
                int(130 + 40 * alpha),
                int(40 + 90 * alpha),
            )
            cv2.line(canvas, (0, y), (canvas.shape[1], y), color, 1)

    @staticmethod
    def _draw_text(
        canvas: np.ndarray,
        text: str,
        origin: tuple[int, int],
        scale: float,
        color: tuple[int, int, int],
        thickness: int,
    ) -> None:
        cv2.putText(
            canvas,
            text,
            origin,
            cv2.FONT_HERSHEY_SIMPLEX,
            scale,
            color,
            thickness,
            cv2.LINE_AA,
        )

    @staticmethod
    def _draw_section_box(
        canvas: np.ndarray,
        top_left: tuple[int, int],
        bottom_right: tuple[int, int],
        title: str,
    ) -> None:
        cv2.rectangle(canvas, top_left, bottom_right, (220, 225, 235), -1)
        cv2.rectangle(canvas, top_left, bottom_right, (176, 186, 202), 2)
        cv2.putText(
            canvas,
            title,
            (top_left[0] + 20, top_left[1] + 40),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.82,
            (18, 32, 54),
            2,
            cv2.LINE_AA,
        )
