import type {
  FitPreference,
  MeasurementValue,
  ReturnRiskLevel,
} from '@/types/smartfit';

interface ShareCardInput {
  profileName: string;
  predictedSize: string;
  confidence: number;
  fitPreference: FitPreference;
  measurements: Record<string, MeasurementValue>;
  brandMapping: Record<string, string>;
  riskLevel: ReturnRiskLevel;
}

export const downloadFitCard = (input: ShareCardInput) => {
  const canvas = document.createElement('canvas');
  canvas.width = 1080;
  canvas.height = 1320;

  const ctx = canvas.getContext('2d');
  if (!ctx) {
    return;
  }

  const gradient = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
  gradient.addColorStop(0, '#0891b2');
  gradient.addColorStop(0.45, '#0f172a');
  gradient.addColorStop(1, '#f97316');

  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.fillStyle = 'rgba(255,255,255,0.95)';
  ctx.fillRect(72, 72, canvas.width - 144, canvas.height - 144);

  ctx.fillStyle = '#0f172a';
  ctx.font = 'bold 64px Space Grotesk, sans-serif';
  ctx.fillText('SmartFit AI', 130, 180);

  ctx.font = '500 30px Manrope, sans-serif';
  ctx.fillStyle = '#334155';
  ctx.fillText(`Profile: ${input.profileName}`, 130, 240);

  ctx.fillStyle = '#0369a1';
  ctx.font = '700 36px Space Grotesk, sans-serif';
  ctx.fillText(`Predicted Size: ${input.predictedSize}`, 130, 330);

  ctx.fillStyle = '#334155';
  ctx.font = '500 26px Manrope, sans-serif';
  ctx.fillText(`Confidence: ${input.confidence}%`, 130, 380);
  ctx.fillText(`Fit Preference: ${input.fitPreference}`, 130, 425);
  ctx.fillText(`Return Risk: ${input.riskLevel}`, 130, 470);

  ctx.fillStyle = '#0f172a';
  ctx.font = '700 30px Space Grotesk, sans-serif';
  ctx.fillText('Measurements', 130, 560);

  ctx.font = '500 24px Manrope, sans-serif';
  let y = 610;
  Object.entries(input.measurements)
    .slice(0, 6)
    .forEach(([key, value]) => {
      const label = key.replace(/[_-]+/g, ' ');
      ctx.fillText(`${label}: ${value}`, 130, y);
      y += 44;
    });

  ctx.font = '700 30px Space Grotesk, sans-serif';
  ctx.fillStyle = '#0f172a';
  ctx.fillText('Brand Mapping', 130, 930);

  ctx.font = '500 24px Manrope, sans-serif';
  y = 980;
  Object.entries(input.brandMapping)
    .slice(0, 6)
    .forEach(([brand, size]) => {
      ctx.fillText(`${brand}: ${size}`, 130, y);
      y += 42;
    });

  ctx.fillStyle = '#475569';
  ctx.font = '500 20px Manrope, sans-serif';
  ctx.fillText('Generated by SmartFit AI', 130, 1190);

  const dataUrl = canvas.toDataURL('image/png');
  const link = document.createElement('a');
  link.href = dataUrl;
  link.download = `smartfit-profile-${Date.now()}.png`;
  link.click();
};
